Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
files = sorted(glob.glob('../../data/surface-meteorology/*/*/*/*.nc'))

ds = xr.open_mfdataset(files[-60:])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m files [38;5;241m=[39m [38;5;28msorted[39m(glob[38;5;241m.[39mglob([38;5;124m'[39m[38;5;124m../../data/surface-meteorology/*/*/*/*.nc[39m[38;5;124m'[39m))
[0;32m----> 3[0m ds [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_mfdataset[49m[43m([49m[43mfiles[49m[43m[[49m[38;5;241;43m-[39;49m[38;5;241;43m60[39;49m[43m:[49m[43m][49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/xarray/backends/api.py:1010[0m, in [0;36mopen_mfdataset[0;34m(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)[0m
[1;32m    997[0m     combined [38;5;241m=[39m _nested_combine(
[1;32m    998[0m         datasets,
[1;32m    999[0m         concat_dims[38;5;241m=[39mconcat_dim,
[0;32m   (...)[0m
[1;32m   1005[0m         combine_attrs[38;5;241m=[39mcombine_attrs,
[1;32m   1006[0m     )
[1;32m   1007[0m [38;5;28;01melif[39;00m combine [38;5;241m==[39m [38;5;124m"[39m[38;5;124mby_coords[39m[38;5;124m"[39m:
[1;32m   1008[0m     [38;5;66;03m# Redo ordering from coordinates, ignoring how they were ordered[39;00m
[1;32m   1009[0m     [38;5;66;03m# previously[39;00m
[0;32m-> 1010[0m     combined [38;5;241m=[39m [43mcombine_by_coords[49m[43m([49m
[1;32m   1011[0m [43m        [49m[43mdatasets[49m[43m,[49m
[1;32m   1012[0m [43m        [49m[43mcompat[49m[38;5;241;43m=[39;49m[43mcompat[49m[43m,[49m
[1;32m   1013[0m [43m        [49m[43mdata_vars[49m[38;5;241;43m=[39;49m[43mdata_vars[49m[43m,[49m
[1;32m   1014[0m [43m        [49m[43mcoords[49m[38;5;241;43m=[39;49m[43mcoords[49m[43m,[49m
[1;32m   1015[0m [43m        [49m[43mjoin[49m[38;5;241;43m=[39;49m[43mjoin[49m[43m,[49m
[1;32m   1016[0m [43m        [49m[43mcombine_attrs[49m[38;5;241;43m=[39;49m[43mcombine_attrs[49m[43m,[49m
[1;32m   1017[0m [43m    [49m[43m)[49m
[1;32m   1018[0m [38;5;28;01melse[39;00m:
[1;32m   1019[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1020[0m         [38;5;124m"[39m[38;5;132;01m{}[39;00m[38;5;124m is an invalid option for the keyword argument[39m[38;5;124m"[39m
[1;32m   1021[0m         [38;5;124m"[39m[38;5;124m ``combine``[39m[38;5;124m"[39m[38;5;241m.[39mformat(combine)
[1;32m   1022[0m     )

File [0;32m/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/xarray/core/combine.py:975[0m, in [0;36mcombine_by_coords[0;34m(data_objects, compat, data_vars, coords, fill_value, join, combine_attrs, datasets)[0m
[1;32m    973[0m     concatenated_grouped_by_data_vars [38;5;241m=[39m []
[1;32m    974[0m     [38;5;28;01mfor[39;00m [38;5;28mvars[39m, datasets_with_same_vars [38;5;129;01min[39;00m grouped_by_vars:
[0;32m--> 975[0m         concatenated [38;5;241m=[39m [43m_combine_single_variable_hypercube[49m[43m([49m
[1;32m    976[0m [43m            [49m[38;5;28;43mlist[39;49m[43m([49m[43mdatasets_with_same_vars[49m[43m)[49m[43m,[49m
[1;32m    977[0m [43m            [49m[43mfill_value[49m[38;5;241;43m=[39;49m[43mfill_value[49m[43m,[49m
[1;32m    978[0m [43m            [49m[43mdata_vars[49m[38;5;241;43m=[39;49m[43mdata_vars[49m[43m,[49m
[1;32m    979[0m [43m            [49m[43mcoords[49m[38;5;241;43m=[39;49m[43mcoords[49m[43m,[49m
[1;32m    980[0m [43m            [49m[43mcompat[49m[38;5;241;43m=[39;49m[43mcompat[49m[43m,[49m
[1;32m    981[0m [43m            [49m[43mjoin[49m[38;5;241;43m=[39;49m[43mjoin[49m[43m,[49m
[1;32m    982[0m [43m            [49m[43mcombine_attrs[49m[38;5;241;43m=[39;49m[43mcombine_attrs[49m[43m,[49m
[1;32m    983[0m [43m        [49m[43m)[49m
[1;32m    984[0m         concatenated_grouped_by_data_vars[38;5;241m.[39mappend(concatenated)
[1;32m    986[0m [38;5;28;01mreturn[39;00m merge(
[1;32m    987[0m     concatenated_grouped_by_data_vars,
[1;32m    988[0m     compat[38;5;241m=[39mcompat,
[0;32m   (...)[0m
[1;32m    991[0m     combine_attrs[38;5;241m=[39mcombine_attrs,
[1;32m    992[0m )

File [0;32m/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/xarray/core/combine.py:648[0m, in [0;36m_combine_single_variable_hypercube[0;34m(datasets, fill_value, data_vars, coords, compat, join, combine_attrs)[0m
[1;32m    646[0m     indexes [38;5;241m=[39m concatenated[38;5;241m.[39mindexes[38;5;241m.[39mget(dim)
[1;32m    647[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m (indexes[38;5;241m.[39mis_monotonic_increasing [38;5;129;01mor[39;00m indexes[38;5;241m.[39mis_monotonic_decreasing):
[0;32m--> 648[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    649[0m             [38;5;124m"[39m[38;5;124mResulting object does not have monotonic[39m[38;5;124m"[39m
[1;32m    650[0m             [38;5;124m"[39m[38;5;124m global indexes along dimension [39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(dim)
[1;32m    651[0m         )
[1;32m    653[0m [38;5;28;01mreturn[39;00m concatenated

[0;31mValueError[0m: Resulting object does not have monotonic global indexes along dimension station

