Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
if minute_ds is not None:
    WindDisplay = act.plotting.WindRoseDisplay(minute_ds, figsize=(6, 8), subplot_shape=(1,))
    WindDisplay.plot(
        'wind_direction', 'wind_speed', spd_bins=np.linspace(0, 20, 5), num_dirs=30, tick_interval=2, subplot_index=(0,)
    )
    plt.show()
else:
    print('Issue with wxt datastream')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [38;5;28;01mif[39;00m [43mminute_ds[49m [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m      2[0m     WindDisplay [38;5;241m=[39m act[38;5;241m.[39mplotting[38;5;241m.[39mWindRoseDisplay(minute_ds, figsize[38;5;241m=[39m([38;5;241m6[39m, [38;5;241m8[39m), subplot_shape[38;5;241m=[39m([38;5;241m1[39m,))
[1;32m      3[0m     WindDisplay[38;5;241m.[39mplot(
[1;32m      4[0m         [38;5;124m'[39m[38;5;124mwind_direction[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mwind_speed[39m[38;5;124m'[39m, spd_bins[38;5;241m=[39mnp[38;5;241m.[39mlinspace([38;5;241m0[39m, [38;5;241m20[39m, [38;5;241m5[39m), num_dirs[38;5;241m=[39m[38;5;241m30[39m, tick_interval[38;5;241m=[39m[38;5;241m2[39m, subplot_index[38;5;241m=[39m([38;5;241m0[39m,)
[1;32m      5[0m     )

[0;31mNameError[0m: name 'minute_ds' is not defined

